export const UPDATE_FIELDS_ORGANIZER = 'UPDATE_FIELDS';
export const BLUR_FIELDS_ORGANIZER = 'BLUR_FIELDS';
export const STATE_CLEANUP = 'STATE_CLEANUP';
export const ORGANIZE_REQ = 'ORGANIZE_REQ';
export const ORGANIZE_SUCCESS = 'ORGANIZE_SUCCESS';
export const ORGANIZE_FAILURE = 'ORGANIZE_FAILURE';
export const SET_DATE = 'SET_DATE';