export const REVERSE_GEOCODING_SUCCESS = 'REVERSE_GEOCODING_SUCCESS';
export const LOCATION_REQ = 'LOCATION_REQ';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_FAILURE = 'LOCATION_FAILURE';
export const STATE_CLEANUP = 'STATE_CLEANUP';
