/* eslint-disable prettier/prettier */
export const UPDATE_FIELDS_CHANGE = 'UPDATE_FIELDS_CHANGE';
export const CHANGE_REQ = 'CHANGE_REQ';
export const CHANGE_REQ_SUCCESS = 'CHANGE_REQ_SUCCESS';
export const CHANGE_REQ_FAILURE = 'CHANGE_REQ_FAILURE';
export const BLUR_FIELDS_CHANGE = 'BLUR_FIELDS_CHANGE';
export const STATE_CLEANUP_CHANGE = 'STATE_CLEANUP_CHANGE';
export const RESET_DONE_STATE = 'RESET_DONE_STATE';
