export const DRIVE_FIND_REQ = 'DRIVE_FIND_REQ';
export const DRIVE_FIND_FAILURE = 'DRIVE_FIND_FAILURE';
export const DRIVE_FIND_SUCCESS = 'DRIVE_FIND_SUCCESS';
export const DRIVE_REGISTER_SUCCESS = 'DRIVE_REGISTER-SUCCESS';
export const UPDATE_FIELDS_DRIVE_FILTER = 'UPDATE_FIELDS_DRIVE_FILTER';
export const BLUR_FIELDS_DRIVE_FILTER = 'BLUR_FIELDS_DRIVE_FILTER';
export const STATE_CLEANUP = 'STATE_CLEANUP';