export const SALES_REQ = 'SALES_REQ';
export const SALES_SUCCESS = 'SALES_SUCCESS';
export const SALES_FAILURE = 'SALES_FAILURE';
export const UPDATE_MONTH = 'UPDATE_MONTH';
export const UPDATE_YEAR = 'UPDATE_YEAR';
export const GET_CURRENT_MONTH = 'GET_CURRENT_MONTH';
export const GET_REQUESTED_MONTH = 'CURRENT_MONTH_SUCCESS';
export const GET_THIS_MONTH = 'GET_THIS_MONTH';
export const SET_TODAY = 'SET_TODAY';
export const GET_REQUESTED_BREAKOUT = 'GET_REQUESTED_BREAKOUT';
export const STOCK_INFO = 'STOCK_INFO'
export const YEAR_SUCCESS = 'YEAR_SUCCESS'
export const CURRENT_MONTH_SUCCESS = 'CURRENT_MONTH_SUCCESS'



export const MONTH_REASON_SUCCESS = 'MONTH_REASON_SUCCESS'
export const MONTH_REVENUE_SUCCESS = 'MONTH_REVENUE_SUCCESS'
export const MONTH_SOLD_SUCCESS = 'MONTH_SOLD_SUCCESS'
export const MONTH_BOUGHT_SUCCESS = 'MONTH_BOUGHT_SUCCESS'
export const MONTH_SPENT_SUCCESS = 'MONTH_SPENT_SUCCESS'

export const CURRENT_MONTH_REASON_SUCCESS = 'CURRENT_MONTH_REASON_SUCCESS'
export const CURRENT_MONTH_SOLD_SUCCESS = 'CURRENT_MONTH_SOLD_SUCCESS'
export const CURRENT_MONTH_BOUGHT_SUCCESS = 'CURRENT_MONTH_BOUGHT_SUCCESS'
export const CURRENT_MONTH_SPENT_SUCCESS = 'CURRENT_MONTH_SPENT_SUCCESS'