export const SALES_REQ = 'SALES_REQ';
export const SALES_SUCCESS = 'SALES_SUCCESS';
export const SALES_FAILURE = 'SALES_FAILURE';
export const UPDATE_MONTH = 'UPDATE_MONTH';
export const UPDATE_YEAR = 'UPDATE_YEAR';
export const GET_CURRENT_MONTH = 'GET_CURRENT_MONTH';
export const GET_REQUESTED_MONTH = 'CURRENT_MONTH_SUCCESS';
