export const NOTIFICATIONS_REQ = 'NOTIFICATIONS_REQ';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAILURE = 'NOTIFICATIONS_FAILURE';
export const NOTIFICATION_STATUS_SET = 'NOTIFICATION_STATUS_SET';
