export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN';
export const LOGIN_REQ = 'LOGIN_REQ';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQ = 'REGISTER_REQ,';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS,';
export const REGISTER_FAILURE = 'REGISTER_FAILURE,';
export const LOGOUT = 'LOGOUT';
